### ISSUE TITLE
为本项目添加LICENSE的建议

### ISSUE THREAD

**Issue by muziing** [penway/WDC#1]
我注意到本项目缺乏开源许可证文件。

建议作者添加 `LICENSE`，明确使用何种协议开源。就我个人理解，没有开源许可的项目从某种意义上失去开源的意义：社区其他开发者无法使用这样的项目的代码，也很难为其进行贡献。

**Comment by penway** [comment]
收到，已添加；同时欢迎直接贡献本仓库。
