### ISSUE TITLE
为本项目添加dev分支的建议

### ISSUE THREAD

**Issue by muziing** [penway/WDC#2]
我正在尝试为本项目提交一个Pr，然而我注意到原始仓库中只有一个 `trunk` git 主分支，没有其他分支。

出于安全与多人协作开发之考虑，建议在主分支外添加一个开发分支（如命名为 `dev` 或其他）。然后将主分支保护，只接受 Pr 而不接受直接在 `trunk` 分支上修改。每次开发新功能时，从主分支上签出一个新分支进行开发，这样即使新功能开发尚未完成，也可随时签回主分支接受修复 bug 的 Pr。

**Comment by penway** [comment]
感谢建议，已经添加 dev 分支。
